[2021-03-05 13:47:19 +0530] [4906] [INFO] Starting gunicorn 19.10.0
[2021-03-05 13:47:19 +0530] [4906] [INFO] Listening at: http://127.0.0.1:8000 (4906)
[2021-03-05 13:47:19 +0530] [4906] [INFO] Using worker: sync
[2021-03-05 13:47:19 +0530] [4983] [INFO] Booting worker with pid: 4983
[2021-03-05 13:47:19 +0530] [4984] [INFO] Booting worker with pid: 4984
[2021-03-05 13:47:19 +0530] [4985] [INFO] Booting worker with pid: 4985
[2021-03-05 13:47:19 +0530] [4986] [INFO] Booting worker with pid: 4986
[2021-03-05 13:47:19 +0530] [4987] [INFO] Booting worker with pid: 4987
[2021-03-05 13:47:19 +0530] [4988] [INFO] Booting worker with pid: 4988
[2021-03-05 13:51:49 +0530] [4906] [CRITICAL] WORKER TIMEOUT (pid:4984)
[2021-03-05 13:51:49 +0530] [4984] [ERROR] Error handling request /api/method/frappe.desk.page.setup_wizard.setup_wizard.setup_complete
Traceback (most recent call last):
  File "/home/hp/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/hp/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/hp/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/hp/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/hp/frappe-bench/apps/frappe/frappe/__init__.py", line 1071, in call
    return fn(*args, **newargs)
  File "/home/hp/frappe-bench/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 72, in setup_complete
    task.get('fn')(task.get('args'))
  File "/home/hp/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 95, in setup_company
    fixtures.install_company(args)
  File "/home/hp/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/operations/install_fixtures.py", line 396, in install_company
    make_records(records)
  File "/home/hp/frappe-bench/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 392, in make_records
    doc.insert(ignore_permissions=True)
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in insert
    self.run_post_save_methods()
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 927, in run_post_save_methods
    self.run_method("on_update")
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/hp/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 107, in on_update
    install_country_fixtures(self.name)
  File "/home/hp/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 419, in install_country_fixtures
    frappe.get_attr(module_name)(company_doc, False)
  File "/home/hp/frappe-bench/apps/erpnext/erpnext/regional/india/setup.py", line 14, in setup
    setup_company_independent_fixtures()
  File "/home/hp/frappe-bench/apps/erpnext/erpnext/regional/india/setup.py", line 21, in setup_company_independent_fixtures
    make_custom_fields()
  File "/home/hp/frappe-bench/apps/erpnext/erpnext/regional/india/setup.py", line 548, in make_custom_fields
    create_custom_fields(custom_fields, update=update)
  File "/home/hp/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 143, in create_custom_fields
    create_custom_field(doctype, df, ignore_validate=ignore_validate)
  File "/home/hp/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 127, in create_custom_field
    custom_field.insert()
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in insert
    self.run_post_save_methods()
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 927, in run_post_save_methods
    self.run_method("on_update")
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/hp/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 65, in on_update
    frappe.db.updatedb(self.dt)
  File "/home/hp/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 291, in updatedb
    db_table.sync()
  File "/home/hp/frappe-bench/apps/frappe/frappe/database/schema.py", line 37, in sync
    self.alter()
  File "/home/hp/frappe-bench/apps/frappe/frappe/database/mariadb/schema.py", line 75, in alter
    frappe.db.sql(query)
  File "/home/hp/frappe-bench/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 691, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/gunicorn/workers/base.py", line 202, in handle_abort
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/werkzeug/local.py", line 231, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
    resp = f(*args[:-2] + (request,))
  File "/home/hp/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    frappe.db.rollback()
  File "/home/hp/frappe-bench/apps/frappe/frappe/database/database.py", line 753, in rollback
    self.sql("rollback")
  File "/home/hp/frappe-bench/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 750, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
[2021-03-05 13:51:49 +0530] [4984] [INFO] Worker exiting (pid: 4984)
[2021-03-05 13:51:49 +0530] [5090] [INFO] Booting worker with pid: 5090
[2021-03-05 14:28:38 +0530] [4906] [CRITICAL] WORKER TIMEOUT (pid:5090)
[2021-03-05 14:28:38 +0530] [5090] [ERROR] Error handling request /api/method/frappe.desk.form.save.savedocs
Traceback (most recent call last):
  File "/home/hp/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/hp/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/hp/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/hp/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/hp/frappe-bench/apps/frappe/frappe/__init__.py", line 1071, in call
    return fn(*args, **newargs)
  File "/home/hp/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in insert
    self.run_post_save_methods()
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 927, in run_post_save_methods
    self.run_method("on_update")
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/hp/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 107, in on_update
    install_country_fixtures(self.name)
  File "/home/hp/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 419, in install_country_fixtures
    frappe.get_attr(module_name)(company_doc, False)
  File "/home/hp/frappe-bench/apps/erpnext/erpnext/regional/india/setup.py", line 14, in setup
    setup_company_independent_fixtures()
  File "/home/hp/frappe-bench/apps/erpnext/erpnext/regional/india/setup.py", line 21, in setup_company_independent_fixtures
    make_custom_fields()
  File "/home/hp/frappe-bench/apps/erpnext/erpnext/regional/india/setup.py", line 548, in make_custom_fields
    create_custom_fields(custom_fields, update=update)
  File "/home/hp/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 143, in create_custom_fields
    create_custom_field(doctype, df, ignore_validate=ignore_validate)
  File "/home/hp/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 127, in create_custom_field
    custom_field.insert()
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in insert
    self.run_post_save_methods()
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 927, in run_post_save_methods
    self.run_method("on_update")
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/hp/frappe-bench/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/hp/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 65, in on_update
    frappe.db.updatedb(self.dt)
  File "/home/hp/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 291, in updatedb
    db_table.sync()
  File "/home/hp/frappe-bench/apps/frappe/frappe/database/schema.py", line 37, in sync
    self.alter()
  File "/home/hp/frappe-bench/apps/frappe/frappe/database/mariadb/schema.py", line 75, in alter
    frappe.db.sql(query)
  File "/home/hp/frappe-bench/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 691, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/gunicorn/workers/base.py", line 202, in handle_abort
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/werkzeug/local.py", line 231, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
    resp = f(*args[:-2] + (request,))
  File "/home/hp/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    frappe.db.rollback()
  File "/home/hp/frappe-bench/apps/frappe/frappe/database/database.py", line 753, in rollback
    self.sql("rollback")
  File "/home/hp/frappe-bench/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/hp/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 750, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
[2021-03-05 14:28:38 +0530] [5090] [INFO] Worker exiting (pid: 5090)
[2021-03-05 14:28:38 +0530] [5911] [INFO] Booting worker with pid: 5911
[2021-03-05 15:29:57 +0530] [4906] [CRITICAL] WORKER TIMEOUT (pid:4983)
[2021-03-05 15:29:57 +0530] [4983] [INFO] Worker exiting (pid: 4983)
[2021-03-05 15:29:57 +0530] [8027] [INFO] Booting worker with pid: 8027
[2021-03-05 15:33:58 +0530] [4906] [CRITICAL] WORKER TIMEOUT (pid:4985)
[2021-03-05 15:33:58 +0530] [4985] [INFO] Worker exiting (pid: 4985)
[2021-03-05 15:33:58 +0530] [8216] [INFO] Booting worker with pid: 8216
[2021-03-05 15:36:07 +0530] [4906] [CRITICAL] WORKER TIMEOUT (pid:4988)
[2021-03-05 15:36:07 +0530] [4988] [INFO] Worker exiting (pid: 4988)
[2021-03-05 15:36:07 +0530] [8240] [INFO] Booting worker with pid: 8240
[2021-03-05 15:38:20 +0530] [4906] [CRITICAL] WORKER TIMEOUT (pid:8240)
[2021-03-05 15:38:20 +0530] [8240] [INFO] Worker exiting (pid: 8240)
[2021-03-05 15:38:20 +0530] [8278] [INFO] Booting worker with pid: 8278
WARNING	Property: Unknown Property name. [11:3: overflow-wrap]
WARNING	Property: Unknown Property name. [11:3: overflow-wrap]
WARNING	Property: Unknown Property name. [11:3: overflow-wrap]
